### ISSUE TITLE
Build fails on latest nightly due to repeated identifier

### ISSUE THREAD

**Issue by str4d** [rust-bakery/cookie-factory#31]
```
$ rustc +nightly --version
rustc 1.43.0-nightly (07a34df18 2020-02-08)
$ cargo +nightly build
...
   Compiling cookie-factory v0.3.0
error[E0415]: identifier `s` is bound more than once in this parameter list
   --> /home/str4d/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-factory-0.3.0/src/internal.rs:144:36
    |
144 |     fn skip(s: WriteContext<Self>, s: usize) -> GenResult<Self>
    |                                    ^ used as parameter more than once

error: aborting due to previous error

For more information about this error, try `rustc --explain E0415`.
error: could not compile `cookie-factory`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Builds fine with latest stable (1.41.0).

**Comment by str4d** [comment]
Ah, I see this was fixed in bf150f55e91f800e9ee79ca0e8425cca7bcbfb54. I'll leave this issue open though (until an update is published) so that others can see it has been addressed.

**Comment by Keruspe** [comment]
@Geal just released 0.3.1
